#version: '3' 
services:  
  web:     
    build: .
#    command: pwd && bash ./run.sh
  postgres:
    image: postgres:11
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: OlgaF
      POSTGRES_DB: forum