common:
  port: 8080 # порт, на котором будет запускаться наше приложение
postgres:
  database_url: $DATABASE_URL
#  database_url: postgres://OlgaF:Qwerty123!@localhost:5433/forum
  require_ssl: false # стоит ли шифровать соединение с базой